"""Make password_hash nullable

Revision ID: 49321778b0ea
Revises: ecefaf8191d6
Create Date: 2025-09-23 15:41:41.291235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49321778b0ea'
down_revision = 'ecefaf8191d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
